### ISSUE TITLE
download GeoYFCC

### ISSUE THREAD

**Issue by devinxzhang** [abhimanyudubey/GeoYFCC#4]
Hi~it is an awesome work to collect such a large dataset for domain generalization! Could you please share a script to download the dataset? Many Thanks!

**Comment by abhimanyudubey** [comment]
Hi @DevinCheung , unfortunately the dataset is a subset of YFCC and due to the license we cannot share the download script / host the images. It is available on S3 here: http://multimedia-commons.s3-website-us-west-2.amazonaws.com/, you can use a custom script to download these images. Hope this helps!
